language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
services:
  - mongodb
env:
  - MONGO_URL="mongodb://localhost/mongoconnection"
before_script:
  - sleep 15
script: "npm run test-travis"
after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
