language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
services:
  - mongodb
env:
  - MONGO_CONNECTION_STRING="mongodb://test:test@localhost/test"
before_script:
  - sleep 15
  - mongo test --eval 'db.addUser("test", "test");'
